const SUPABASE_URL="https://wmdqayyqxzejypuwvtzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY="sb_publishable_jvnVs92FjUV9g5xF9i2N_Q_t_5mC0yt";
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const loginView=document.getElementById("loginView"),adminView=document.getElementById("adminView"),loginForm=document.getElementById("loginForm"),loginMsg=document.getElementById("loginMsg"),tablesEl=document.getElementById("tables"),logout=document.getElementById("logout"),statusEl=document.getElementById("status");
async function boot(){const {data:{session}}=await sb.auth.getSession();showSession(session);sb.auth.onAuthStateChange((_event,session)=>showSession(session));}
function showSession(session){const logged=!!session;loginView.hidden=logged;adminView.hidden=!logged;logout.hidden=!logged;if(logged)loadTables();}
loginForm.addEventListener("submit",async e=>{e.preventDefault();loginMsg.textContent="Entrando…";const {error}=await sb.auth.signInWithPassword({email:email.value.trim(),password:password.value});loginMsg.textContent=error?error.message:"";});
logout.addEventListener("click",()=>sb.auth.signOut());
async function loadTables(){statusEl.textContent="Cargando mesas…";const {data,error}=await sb.from("mesas").select("id,numero,estado,capacidad").order("numero");if(error){statusEl.textContent="Error: "+error.message;return}statusEl.textContent=`${data.filter(x=>x.estado==="disponible").length} disponibles · ${data.length} mesas`;tablesEl.innerHTML=data.map(t=>{const free=t.estado==="disponible";return `<article class="table ${free?"available-card":"busy-card"}"><span class="state ${free?"available":"busy"}">${free?"DISPONIBLE":"OCUPADA"}</span><span class="num">Mesa ${t.numero}</span><span class="meta">Hasta ${t.capacidad} personas</span><button type="button" data-id="${t.id}" data-state="${free?"ocupada":"disponible"}">${free?"Marcar ocupada":"Marcar disponible"}</button></article>`}).join("");tablesEl.querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>updateTable(b.dataset.id,b.dataset.state)));if(window.__channel)return;window.__channel=sb.channel("lume-admin-tables").on("postgres_changes",{event:"*",schema:"public",table:"mesas"},loadTables).subscribe();}
async function updateTable(id,state){const {error}=await sb.from("mesas").update({estado:state}).eq("id",id);if(error)alert(error.message);else loadTables();}
boot();
